name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: 7.0.100
    
    # dotnet build and publish
    - name: Publish .NET Core Project
      run: dotnet publish Blazor-Clarity.csproj -c Release -o release --nologo 
